tikv/grpc-rs

src/async/mod.rs
src/call/mod.rs
src/env.rs

It's confusing when there are both Callback and Promise in enum Promise. So I rename enum Promise to CallTag to make it more clear and straightforward.

rename enum Promise to CallTag

---

src/async/promise.rs
src/call/mod.rs
src/call/server.rs
src/lib.rs

So user can use `RpcStatusCode` without adding grpc-sys as dependency explicitly.

reexport RpcStatusCode

---

grpc-sys/src/lib.rs
src/async/mod.rs
src/env.rs
src/lib.rs

So the old API won't break and it will be more convenient to add extra configuration in the future.

use builder to specify custom name prefix instead

---

grpc-sys/Cargo.toml
grpc-sys/build.rs

Only depend on cmake when necessary.

grpc-sys: adjust dependency

---

src/async/mod.rs
src/call/mod.rs
src/call/server.rs

When client stops requesting earlier, server should stop receiving any further requests.

server: support stop early

---

src/call/client.rs
src/call/mod.rs
src/error.rs

Because call can be obtained from `ShareCall`, so `CallHolder` is unnecessary.

remove CallHolder

---

.travis.yml

rustfmt just gets upgraded and its format changes again. Let's remove the check for now, we may need to figure out a long-term policy later.

travis: remove rustfmt check

---

.gitmodules
grpc-sys/build.rs

If we are going to publish this project to *crates.io*, it will be more appropriate to use submodule instead of downloading sources at compile time.
To use the official release, we need to wait till grpc/grpc#11565 is merged.

grpc-sys: use submodule instead

---

appveyor.yml
benchmark/src/util.rs
grpc-sys/build.rs

After this pr, this project should be able to be built and tested on windows. We may need to adopt Appveyor CI later.
If you are using Visual Studio 2017, you may need to use latest nightly rustc to build any rust program.
If you meet code page related error, you may need to set environment `_CL_` to "/utf-8".

build: support build and test on windows

---

src/channel.rs

From 1.6.0 forward, grpc support setting an optimization target for channel, which may be helpful for tuning performance.

channel: support set optimization target

---

benchmark/src/bench.rs
benchmark/src/client.rs
benchmark/src/server.rs
proto/proto/example/helloworld.proto
proto/proto/example/route_guide.proto
proto/proto/grpc/testing/control.proto
proto/proto/grpc/testing/empty.proto
proto/proto/grpc/testing/messages.proto
proto/proto/grpc/testing/payloads.proto
proto/proto/grpc/testing/services.proto
proto/proto/grpc/testing/stats.proto
proto/proto/grpc/testing/test.proto

gRPC 1.6.1 changes its licenses and adds custom channel args when configure benchmark.

benchmark: update to 1.6.1

---

src/async/executor.rs
src/lib.rs

Previously we can't see `StreamingCallSink` in document. This PR fix this.

*: expose StreamingCallSink into documents.

---

Cargo.toml
benchmark/Cargo.toml
benchmark/src/bench.rs
benchmark/src/client.rs
benchmark/src/lib.rs
benchmark/src/main.rs
benchmark/src/server.rs
benchmark/src/worker.rs
examples/hello_world/client.rs
examples/hello_world/server.rs
examples/route_guide/client.rs
examples/route_guide/server.rs
grpc-sys/src/lib.rs
interop/Cargo.toml
interop/src/bin/server.rs
interop/src/client.rs
interop/src/lib.rs
interop/src/server.rs
proto/Cargo.toml
proto/src/lib.rs
proto/src/util.rs
src/async/executor.rs
src/lib.rs
src/log_util.rs

When we want to debug grpc, its log will output to stderr which is not useful for deployment. So this pr provides a function that can redirect grpc log to the standard rust log.

*: support log

---

.travis.yml
Cargo.toml
appveyor.yml
benchmark/src/lib.rs
grpc-sys/Cargo.toml
grpc-sys/build.rs

As discussed in pingcap/tikv#198 and considering the solutions other native crates have chosen (sfackler/rust-openssl#653), let's use environment variable to check link target.

use environment variable to select link target

---

appveyor.yml
grpc-sys/grpc_wrap.c

In Rust gRPC FFI declaration, we assumes the call convention is `__cdecl`. However, we set the call convention to `__stdcall` in the actual ABI on Windows, just follow the same way as C# does accidentally. On 64bit target, there is only [one calling convention][1], so `__stdcall` is [accepted and ignored][2] by the msvc compiler, our tests can pass on Windows. But for 32bit target, `__stdcall`  is actually taken into consideration, so our tests can't pass any more.
This pr sets the call convention on Windows to `__cdecl` explicitly.
Close #95.
[1]: https://msdn.microsoft.com/en-us/library/ms235286.aspx
[2]: https://msdn.microsoft.com/en-us/library/zxk0tw93.aspx

grpcio-sys: fix call convention

---

benchmark/src/client.rs
compiler/src/codegen.rs
examples/hello_world/client.rs
examples/route_guide/client.rs
interop/src/client.rs
src/call/client.rs
src/client.rs

There's no reason to require ownership here. We only ever actually use a
reference to the request anyway.
I have a use case where I call a method multiple times in a loop, and
needing to clone the request each time is unnecessarily wasteful.
Bump version to 0.2.0 because this is an incompatible change.

Client methods take a reference to a request

---

Cargo.toml
README.md
compiler/src/util.rs
grpc-sys/Cargo.toml
grpc-sys/build.rs
grpc-sys/src/lib.rs
interop/tests/tests.rs
proto/Cargo.toml
src/channel.rs
src/lib.rs
src/server.rs

So if secure feature is not used, we can drop the dependency of go.
Close #109

allow disabling secure feature

---

grpc-sys/Cargo.toml
grpc-sys/build.rs

I have had complaints from a couple of developers that their builds are
failing on Darwin because clang is defaulting to linking against
libstdc++ on https://github.com/pantsbuild/pants/issues/4975.

Explicitly link against libc++ on Darwin

---

scripts/reset-submodule

So when switching branch/tag, we can cleanup workspace conveniently.

add reset-submodule script

---

benchmark/src/bench.rs
benchmark/src/client.rs
benchmark/src/lib.rs
benchmark/src/server.rs
benchmark/src/worker.rs

This pr fixes an hang-up-forever issue during benchmark.
To add all the stats 1.7.2 introduces, we need a public API and compatible rust-protobuf. See grpc/grpc#13705 and stepancheg/rust-protobuf#260.
/cc #107 #118 
After this pr is merged, I think we are ready to release 0.2.0.

benchmark: fix shutdown failure

---

grpc-sys/src/lib.rs
src/credentials.rs
src/error.rs

This change adds support for authenticating with [Google Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials).
This is necessary to connect to Google APIs via gRPC.

Added support for Google default credentials.

---

README.md

I have a few projects that I'm evaluating switching over to `grpc-rs` from `grpc-rust` and noticed that there was no easy way to invoke `protoc` with the `grpc-rs` compiler plugin so I wrote a crate based on
[protoc-rust](https://crates.io/crates/protoc-rust). This PR just documents that `protoc-grpcio` is another option for module generation for `grpc-rs` users.
Cheers,
Matt

Add documentation on using protoc-grpcio

---

grpc-sys/build.rs

When using `rerun-if-env-changed`, changes in grpc-sys won't trigger a rebuild automatically anymore. This pr fixes it by setting what changes need a rebuild explicitly.

build: trigger build when c sources change

---

benchmark/src/client.rs
benchmark/src/server.rs
src/call/server.rs
src/channel.rs

usize is too large for c int. This pr changes the type from usize to i32, which suits most modern compiler and architect. Also add an assert check that prevent overflow from happening at run time for the others.

channel: fix overflow

---

grpc-sys/build.rs

musl doesn't provide musl-g++, so CMake fails to run when targeting musl
even though grpcio-sys doesn't actually require or use g++. Satisfy
CMake by telling it to use non-musl g++ if we're building for musl.

Fix grpcio-sys building under musl

---

README.md

Part of #149.
The README states:
> If you want to enable secure feature, Go (>=1.7) is required.
Then you'd expect the `secure` feature to be optional and not by default.

Make secure feature optional and not by default

---

grpc-sys/build.rs

Address the issue mentioned in #199.
All CIs pre-install go by default, and there seems to be no configuration entries available to tweak the behavior. So I leave the tests as it is.

build: use fake go when secure feature is disabled

---

src/async/callback.rs
src/async/executor.rs
src/async/mod.rs
src/async/promise.rs
src/call/client.rs
src/call/mod.rs
src/call/server.rs
src/channel.rs
src/client.rs
src/cq.rs
src/credentials.rs
src/env.rs
src/server.rs

Removed redundant variables as pointed out by clippy and some files that might have caused build to fail on travis ci

Reduce warning and remove redundant variables

---

grpc-sys/build.rs
grpc-sys/src/lib.rs
src/async/executor.rs
src/call/client.rs
src/call/mod.rs
src/call/server.rs
src/channel.rs
src/client.rs
src/codec.rs
src/credentials.rs
src/env.rs
src/error.rs
src/lib.rs
src/server.rs

1. Add documentation for most of the public stuffs
2. Rename `<P, Q>` to `<Req, Resp>` to be clear.
3. Add `#[doc(hidden)]` for those internal methods used only in benchmark or tests.
4. rpc -> RPC, grpc -> gRPC.

Add verbose documentations

---

.travis.yml

Also see: https://internals.rust-lang.org/t/clippy-is-available-as-a-rustup-component/7967
Move the clippy we use from being installed by `cargo` to being installed by `rustup`. If you find strange problems with clippy after they are merged you will need to do: `cargo uninstall clippy && cargo uninstall clippy-lints && rustup self update`
This is because the old versions of rustup don't know that clippy is managed, so they give errors like `subcommand clippy does not exist`.
Currently the clippy version must be managed separate from the Rust nightly. Using Rustup will allow each of our projects to depend on their own clippy versions and help avoid some toolchain related problems.
* https://github.com/pingcap/raft-rs/pull/95
* https://github.com/pingcap/rust-prometheus/pull/186
* …

travis: Use rustup provided clippy.

---

grpc-sys/grpc_wrap.c

Address https://github.com/pingcap/grpc-rs/pull/203#issuecomment-406257048.
```diff
diff --git a/.clang-format b/.clang-format
index 4b3f13fa55..f9af7637aa 100644
--- a/.clang-format
+++ b/.clang-format
@@ -1,5 +1,12 @@
---
Language:        Cpp
BasedOnStyle:  Google
+DerivePointerAlignment: false
+PointerAlignment: Left
+---
+Language: ObjC
+BasedOnStyle: Google
+ColumnLimit: 100
+ObjCBlockIndentWidth: 2
...
```

Format grpc_wrap.c with the clang-format from gRPC v1.13.0

---

src/channel.rs
src/lib.rs
tests/cases/misc.rs

The C library implements `round_robin` load balancing. This patch exposes an api to set this option. This fits my use-case.
Debugging with 
```
GRPC_TRACE=client_channel GRPC_VERBOSITY=DEBUG  cargo test 
```
I see it's being used:
```
D0727 13:49:12.471451992    4814 client_channel.c:482]       chand=0x7f5c0ce2b388: resolver result: lb_policy_name="round_robin" (changed), service_config="(null)"
D0727 13:49:12.471457240    4814 client_channel.c:564]       chand=0x7f5c0ce2b388: initializing new LB policy
```

Add load_balancing_policy to ChannelBuilder

---

src/async/callback.rs
src/async/mod.rs
src/call/server.rs
src/server.rs
tests/cases/misc.rs

We use Send + Clone pattern to achieve concurrency without lock.
However our service handler registry treat them as if it's Send + Sync,
which will lead to data race.

*: fix soundness of service handler

---

benchmark/src/bench.rs
benchmark/src/worker.rs
compiler/src/codegen.rs
examples/hello_world/server.rs
examples/route_guide/server.rs
interop/src/server.rs
src/async/callback.rs
src/call/server.rs
src/server.rs
tests/cases/alarm.rs
tests/cases/health_check.rs
tests/cases/metadata.rs
tests/cases/misc.rs

Because service is `Send` + `Clone` and kept only one copy on every
completion queue, it's possible to accept a mut reference instead of an
immutable reference. Accepting a mut reference also allows users to
mutate internal states easily.
This is an incompatible change, should not be merged before #223.

*: make service accept mut reference

---

interop/src/client.rs
src/call/client.rs
src/call/mod.rs
src/call/server.rs
tests/cases/cancel.rs
tests/cases/mod.rs

So we will not accidentally leak gRPC calls.
Cc https://github.com/pingcap/grpc-rs/issues/150

Cancel RPC when senders and receivers are dropped

---

interop/Cargo.toml
interop/src/lib.rs
interop/src/server.rs

gRPC may spawn a thread before deadline callback which may spend more than 10ms.
To stable the test, server should sleep longer.

Stable timeout_on_sleeping_server

---

src/metadata.rs

In the current state, grpc-rs does not allow '.' as a valid character in the key validation function, even though it is a valid character for keys in many other GRPC clients, notably Go, Ruby, and Java.
The most restrictive language I have seen regarding keys is within the official GPRC clients, this for [Java](https://grpc.io/grpc-java/javadoc/io/grpc/Metadata.Key.html) and [Go](https://godoc.org/google.golang.org/grpc/metadata#Pairs) -- it is in alignment to grpc-rs but also allows for '.' characters.
This is currently breaking the addition of a required security header (workload.spiffe.io=true) for the [SPIFFE standard](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_Endpoint.md#3-transport) workload API with this client.

Allow '.' characters in metadata keys

---

.travis.yml
Cargo.toml
grpc-sys/Cargo.toml
grpc-sys/build.rs

This prevent link/runtime failure when you have a crate which uses both
grpc-rs and openssl-rs.
Based on feedback from #186. Build against fresh master.

Optionally use openssl instead of boring ssl.

---

src/call/server.rs
tests/cases/cancel.rs

It's possible that server stream is flushing messages when the connection is closed. So we need to check if the call is still valid inside `poll_complete`.
Close #175.

server: check fail eagerly

---

Cargo.toml
compiler/Cargo.toml
interop/Cargo.toml
proto/Cargo.toml

I wanted to bump these versions to get the  the newly added `serde_derive` support in generated code. stepancheg/rust-protobuf brings this in as of 2.1.

Bump protobuf and protobuf-codegen from ~2.0 -> ~2.1

---

compiler/src/codegen.rs
src/client.rs

This is especially useful for services connecting to other services as it allows to just make the client a member of the struct which implements the *Service trait while using `#[derive(Clone)]`.
Tests:
`cargo test` at the root folder and built one of my own projects with this. Do you have some other tests you would like me to run?

Make the generated *Client classes clonable; This requires making grpcio::Client clonable too

---

src/error.rs

To unblock other PRs, we allow deprecated `Error::cause`.
We should impl `Error::source`, once TiKV uses rust 2018 edition. 
Cc/ https://github.com/tikv/tikv/pull/3952

error: allow deprecated `Error::cause`

---

Cargo.toml
compiler/Cargo.toml
interop/Cargo.toml
proto/Cargo.toml

Changelog: https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#221---2018-12-25

Bump protobuf and protobuf-codegen from ~2.1 -> ~2.2

---

Cargo.toml
compiler/Cargo.toml
interop/Cargo.toml

So users can select protobuf version from "2.0.0" to "3.0.0". 
Cc #272

Cargo: remove tilde requirements of protobuf

---

src/server.rs

If the host is an IPv6 literal, it needs brackets to form a valid address.
Cc https://github.com/tikv/tikv/issues/4136

server: support ipv6 host

---

cross_compile.md
grpc-sys/build.rs

Heya,
This PR makes it possible to cross-compile this crate to Android and iOS, both simulator and real hardware. I have tested it and the resulting code works flawlessly (tested on iPhone 7, iPhone XS, Nexus6P, iPhone simulator and Android simulator).
Building for iOS is as simple as cargo build --target i386-apple-ios/x86_64-apple-ios/armv7-apple-ios armv7s-apple-ios/aarch64-apple-ios
Android is more complicated and requires a bunch of environment variables. For example, on my machine, this is what I used for aarch64-linux-android:
```
PATH=$(PATH):$(NDK_HOME)/toolchains/llvm/prebuilt/darwin-x86_64/bin \
LDFLAGS=-stdlib=libstdc++ \
CFLAGS="-Wno-unused-command-line-argument -DMDB_USE_ROBUST=0" \
CXXFLAGS="-Wno-unused-command-line-argument" \
CXX=aarch64-linux-android26-clang++ \ …
```

make it possible to cross-compile for iOS and Android targets

---

grpc-sys/Cargo.toml
grpc-sys/build.rs

Vendor build implemented in #262 is not configured properly, compiler
will use the system library during compilation. This PR fixes the
problem by configuring package searching path for openssl.

grpcio-sys: fix openssl vendor build

---

benchmark/src/client.rs
grpc-sys/src/lib.rs
proto/Cargo.toml
proto/build.rs
proto/src/lib.rs

1. error: trait objects without an explicit `dyn` are deprecated
2. `Box<trait>` to `Box<dyb trait>`
3. libc has deprecated several types, which are used in grpcio.

grpcio-sys: fix warnings in nightly

---

Cargo.toml
compiler/Cargo.toml
proto/Cargo.toml
src/metadata.rs

Use a Git dep for Prost so we get some optimisations which are not present in the current release.
PTAL @ice1000 @overvenus

Use Git dep for Prost

---

proto/build.rs

rust-protobuf can't detect path correctly, this is a workaround for stepancheg/rust-protobuf#433.

proto: replace slash to get it built on windows

---

.travis.yml
proto/build.rs
scripts/reset-submodule.cmd

Travis by default init all submodules, which is unnecessary. Only
initing required submodules can save some time. For windows platform,
choco seems quite slow, so here manually installing and then caching
dependencies instead

 *: speed up ci

---

benchmark/src/bench.rs
interop/src/client.rs
interop/src/server.rs
src/call/mod.rs
src/call/server.rs
src/task/promise.rs
tests-and-examples/tests/cases/cancel.rs
tests-and-examples/tests/cases/health_check.rs

Give the variable a more descriptive name so we know what kind of a code it is and what the valid values are. Leave grpc-sys untouch and define the type `RpcStatusCode` in grpcio itself.

grpcio: wrap the grpc status code

---

compiler/Cargo.toml
compiler/src/codegen.rs

CodeWriter is not meant to be a public API of protobuf-codegen.
However, protobuf-codegen should export some API to map protobuf
types to rust types, but it doesn't have this API now, so I'm
removing protobuf-codegen dependency.

Copy-paste CodeWriter from protobuf-codegen crate

---

grpc-sys/bindings/x86_64-unknown-linux-gnu-bindings.rs
grpc-sys/grpc_wrap.cc
src/channel.rs
src/lib.rs
src/quota.rs
tests-and-examples/examples/hello_world/server.rs

* Add the `ResourceQuota` struct to control the bound on memory usage.
* Wrap `set_pointer_vtable` to configure channel args.
* Format `grpc_wrap.cc` code style.

grpcio: add resource quota support

---

CHANGELOG.md

Last time i bump v0.3.2 is on 2019-09-10 not 2018-09-10.

Fix change log date typo

---

grpc-sys/build.rs

We should not rely on the assumption that ssl library is in the search
path when enabling openssl features. This PR utilize the path figured by
cmake to link correctly.
Close #330.

grpc-sys: fix ssl path when using openssl

---

src/cq.rs
src/env.rs
src/task/executor.rs
src/task/mod.rs
tests-and-examples/tests/cases/kick.rs

grpcio executor polls futures in place to reduce context switch and for better locality coherence. But it can lead to deadlock. For example, sender and receiver can share memory which is guard by lock. Then deadlock can happen in following event sequences.
```
1. sender lock the shared memory
2.     sender put item into the shared memory
3.     sender notify
4.     grpcio exeuctor poll in place
5.     receiver woken up
6.     receiver lock the shared memory
7.        receiver poll item from shared
```
Step 6 will wait forever as the lock has been held by sender since step 1.
A better way to handle notification is store the readiness in a stack and handle the readiness one by one. Using stack instead of queue for better coherence.

executor: fix deadlock

---

CHANGELOG.md
compiler/Cargo.toml
compiler/src/codegen.rs

Clippy is deprecated. Should use `clippy::all` instead.

compiler: allow clippy all

---

src/channel.rs
src/server.rs

Fixes https://github.com/tikv/grpc-rs/issues/399

doc: make build_args and channel_args public

---

src/call/mod.rs
src/lib.rs

Signed-off-by: qupeng <qupeng@pingcap.com>
If there are too many long term connections, `SinkBase`'s internal buffer could take too much memory. We have located this problem in some situations. This PR shrinks its internal buffer.
Running test cases with the patch, TiKV won't report OOM, and its memory usage becomes stable.

shrink sink internal buffer if need

---

.travis.yml
grpc-sys/Cargo.toml
grpc-sys/build.rs
scripts/reset-submodule.cmd

*: use libz-sys instead of bundled one

---

src/call/mod.rs

Current implementation respects the rules of [`Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html).
Current missing derive prevents use in pattern matching:
```
to use a constant of type `grpcio::call::RpcStatusCode` in a pattern, `grpcio::call::RpcStatusCode` must be annotated with `#[derive(PartialEq, Eq)]`
```

Add `Eq` to `RpcStatusCode` to allow use in pattern matching

---

grpc-sys/build.rs

This fixes the regression introduced by https://github.com/tikv/grpc-rs/commit/0bb4c6079a0c425b83e7df917a483580c555151d#diff-fc1b9721ad58e6a299d6d6633dbc46caR335 and documented on https://github.com/tikv/grpc-rs/issues/449

build: fix rebuild rules for no prebuilt bindings

---

CHANGELOG.md
grpc-sys/Cargo.toml
grpc-sys/build.rs

Due to rust-lang/cargo#5237, upgrading bindgen is not backward
compatible.

grpc-sys: downgrade bindgen

---

README.md
grpc-sys/build.rs

NPN, the Next Protocol Negotiation extension, is specified by [a draft expired 6 years ago](https://tools.ietf.org/html/draft-agl-tls-nextprotoneg-04) and has been replaced by ALPN. So I suggest that we should support its successor ALPN to ensure successful connection to the servers with ALPN only.
Signed-off-by: TXXT <hunterlxt@live.com>

Enable ALPN as default

---

src/env.rs
tests-and-examples/tests/cases/misc.rs

This allows users to manipulate the thread pool created by gRPC. They can add some custom code like print logs for newly created threads and reclaim some resources or record when exiting the thread.
Note: It is recommended to PR pick to 0.5.x

Add blocking callback to EnvBuilder

---

Cargo.toml
grpc-sys/build.rs
proto/Cargo.toml
src/call/server.rs
src/env.rs
tests-and-examples/tests/cases/misc.rs

Pick Add blocking callback to EnvBuilder (#474)

---

benchmark/src/bench.rs
benchmark/src/client.rs
src/call/client.rs
src/call/mod.rs
src/call/server.rs
src/channel.rs
tests-and-examples/Cargo.toml
tests-and-examples/tests/cases/mod.rs
tests-and-examples/tests/cases/stream.rs

close #415 
Optimize `send_all` using sink in grpc-rs. By buffering the message to be sent to determine whether there is still message in the stream, and add the `buffer_hint` flag to indicate follow-up messages.
After a simple test, this does improve the QPS by 50% when you use `send_all` method.
```
Before
======== test_client_stream_send_split
QPS: 13626.411713542033
======== test_client_stream_send_all
QPS: 13458.8795676736
======== test_server_stream_send_all
QPS: 21513.004479575207
After
======== test_client_stream_send_split
QPS: 13632.78241828707
======== test_client_stream_send_all
QPS: 20634.743684214573
======== test_server_stream_send_all
QPS: 21282.527286920154
Tcpdump capture file size (only send_all test)
Before：22M
After：2.6M
```
Related test code: …

Enhance sinks to make them batchable

---

compiler/src/codegen.rs

Codegen emitted an inner `cfg_attr` attribute, which caused problems with stable Rust (according to https://github.com/tikv/raft-rs/issues/390#issuecomment-670342443). This PR removes that line. The user can always add it as an outer attribute if they want to skip formatting.
cc https://github.com/tikv/raft-rs/issues/390
PTAL @BusyJay @overvenus

compiler: do not emit rustfmt_skip inner attr, since it is unstable

---

benchmark/src/bench.rs
grpc-sys/bindings/aarch64-unknown-linux-gnu-bindings.rs
grpc-sys/bindings/x86_64-unknown-linux-gnu-bindings.rs
grpc-sys/grpc_wrap.cc
src/buf.rs
src/call/client.rs
src/call/mod.rs
src/call/server.rs
src/codec.rs
src/lib.rs
src/metadata.rs

Use grpc_slice to reduce memory copy. If the messages are small,
this should reduce allocations.

*: use grpc_slice to avoid copy

---

Cargo.toml

Thanks for maintaining this crate. Some additional context for this change:
We're considering grpc-rs for use in the Android open source project[1]. For Android, it's important that we limit the number of crate versions that are used because that reduces both memory and disk usage, both of critical importance on resource-constrained Android devices. Generally we try to achieve that by only depending on the latest version of each crate that we directly or indirectly use. This change moves us to the most recent version of parking_lot, which also results in updating to the most recent version of a couple of its dependencies.
[1]: https://android-review.googlesource.com/c/platform/external/rust/crates/grpcio/+/1460423

Update parking_lot to version 0.11

---

grpc-sys/build.rs

The `musl-gcc` cross compiler doesn't come with a corresponding
`musl-g++`, so #195 hard-coded the C++ compiler to `g++` when
building for musl. However, this results in building native binaries using
the native compiler, rather than an available musl toolchain (e.g.,
`x86_64-linux-musl-g++`).
This PR modifies the build script to allow the `CXX` environment
variable to override `g++`, even when building for musl.
cc: @csssuf @Hoverbear from #195

Allow CXX environment variable to override g++ for musl build

---

src/call/server.rs
src/lib.rs
src/server.rs
tests-and-examples/tests/cases/misc.rs

Users can provide custom checker to decide if the grpc call should be aborted in advance or be continued. For operations like check common name, a lot of redundant code can be avoided.
Execute the custom closure provided by the user at the `execute` function from `src/call/server.rs`. If the user declares that the grpc call has been aborted, then skip the subsequent grpc handler.

Add user-defined checker for server side

---

proto/Cargo.toml

otherwise it will not compile on hosts that have no pre-generated bindings.

proto: add missing features

---

grpc-sys/build.rs

grpc c core 1.35 requires gcc 4.9+. It usually makes users switch
compiler on failure. But cmake doesn't work well on compiler changes, so
this pr detects the changes early and remove stale cache so that it can
finish compilation.

grpc-sys: detect failure early

---

src/call/mod.rs
src/channel.rs
tests-and-examples/tests/cases/misc.rs

async/await doesn't work well with temporary variables, this PR changes
it to `impl Future` to get around Send requirement.

channel: fix send issue in state change API

---

src/server.rs
tests-and-examples/tests/cases/misc.rs

Abstract UDS is supported in c core with schema `unix-abstract`. This
PR adds supoort for the schema and avoid append additional ":0" suffix.

*: support abstract UDS

---

.github/workflows/ci.yml
.travis.yml
grpc-sys/Cargo.toml
grpc-sys/build.rs
health/src/proto/protobuf/health_grpc.rs
src/call/mod.rs
src/channel.rs

If the secure feature is disabled, it's not needed to compile the boringssl-src crate.
This assume that the `secure` feature is using `boringssl-src` by default which I think is the current behaviour.
A bad aspect of this is that `boringssl-src` will be compiled even if `openssl` is chosen but I think that is currently the case anyway?
Fix #536

Make boringssl-src optional

---

tests-and-examples/tests/cases/stream.rs

Because the service returns early, it's possible the sink finish with
errors.

tests: fix flaky client_send_all case

---

Cargo.toml
compiler/Cargo.toml
health/Cargo.toml
proto/Cargo.toml
tests-and-examples/Cargo.toml
xtask/Cargo.toml

Update Prost to 0.8, to avoid security issue of 0.7 (RUSTSEC-2021-0073).
Related issue: tikv/tikv#10905, https://github.com/tikv/protobuf-build/pull/55
Note that `grpcio-proto` still depends on `prost 0.7` because of its build-dependency to `protobuf-build 0.12`. As `protobuf-build 0.12` depends on `grpcio-compiler 0.9`, there is a circular dependency between `grps-rs` and `protobuf-build`.
I think we should release `grps-rs` 0.10.0 first, then `protobuf-build` 0.13, and at last update `grpcio-proto` to depend on `protobuf-build` 0.13.
Signed-off-by: pingyu <shui.yu@126.com>

Update prost to 0.8

---

grpc-sys/grpc_wrap.cc
proto/Cargo.toml
src/buf.rs
src/call/client.rs
src/call/mod.rs
src/metadata.rs
src/task/mod.rs
src/task/promise.rs

After metadata is received, every entry should be owned by the grpc c
core, application should clone the byte slice if necessary.
In the past, we get around the problem by increasing the reference
count of the slice. However, it's unsafe to do so as the slice is not
guaranteed to be accessible in the first place.
This PR fixes the problem by introducing an unowned metadata type. It
works just like Metadata, but accessing its content requires manual
check for the lifetime of associated call.
I tried to add test case to cover the unsafe access, however it's too racy
and nearly impossible to introduce a case without touching the C core.

metadata: avoid change metadata ref

---

src/channel.rs

As default configuration gRPC will reuse TCP connections to each gRPC server what ever how many channel instance created. This PR will introduce a method to set `grpc.use_local_subchannel_pool` settings to let channel instance use it's own connection pool.

Add method for set use local subchannel pool feature

---

.github/workflows/ci.yml

Confirmed from pingcap that arm self hosted runner is not available anymore, so we need to remove these checks in CI as they will always timeout.

*: remove arm ci check

---

grpc-sys/build.rs

ref #583. Linking is not a problem for musl distros with gcompat.
```
[xhe@PC grpc-rs]$ cargo build
warning: patch for `grpcio-compiler` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
Compiling grpcio-sys v0.10.3+1.44.0-patched (/home/xhe/project/pingcap/grpc-rs/grpc-sys)
Compiling grpcio v0.11.0 (/home/xhe/project/pingcap/grpc-rs)
Finished dev [unoptimized + debuginfo] target(s) in 1m 13s
```

*: fix musl building

---

compiler/src/codegen.rs
compiler/src/prost_codegen.rs
health/src/proto/prost/grpc.health.v1.rs
health/src/proto/protobuf/health_grpc.rs
proto/src/proto/prost/example/helloworld.rs
proto/src/proto/prost/example/routeguide.rs
proto/src/proto/prost/testing/grpc.testing.rs
proto/src/proto/protobuf/example/helloworld_grpc.rs
proto/src/proto/protobuf/example/route_guide_grpc.rs
proto/src/proto/protobuf/testing/services_grpc.rs
proto/src/proto/protobuf/testing/test_grpc.rs
src/channel.rs
src/client.rs

We have supported channel state, but it's very inconvenient without the capability of accessing underlying channel of a client.

client: allow accessing channel

---

grpc-sys/bindings/bindings.rs
grpc-sys/grpc_wrap.cc
src/call/mod.rs

* grpc-sys: provide error string for receive status on client calls
* call: provide debug error string in RpcStatus
* ~error: make Display ouput more human-readable~
* ~call: make Display of RpcStatusCode more human-readable~
Example of contents of `RpcStatus::debug_error_string`:
```
thread 'test_health_watch_multiple' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFailure(RpcStatus { code: 14-UNAVAILABLE, message: "failed to connect to all addresses", details: [], debug_error_string: "{\"created\":\"@1672417943.726323715\",\"description\":\"Failed to pick subchannel\",\"file\":\"/home/rob/grpc-rs/grpc-sys/grpc/src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3217,\"referenced_errors\":[{\"created\":\"@1672417943.726320053\",\"description\":\"failed to …
```

Provide more debugging info for RpcStatus

---

compiler/src/prost_codegen.rs

Make the prost service generator available to clients. This allows
clients to customize how the underlying prost build is invoked.
Signed-off-by: Nick Santana <nick@mobilecoin.com>
---
name: Publicize Prost Service Generator
about: Makes the prost generator a public struct
---
**Description of feature:**
The prost service generator is now public, allowing clients finer grain control on the prost build behavior.
**Implementation:**
The initial desire for this was to allow us to build just the services, while re-using the messages.  The current `grpcio_compiler::prost_codegen::compile_protos()` function would either fail to build when local protos were excluded from the include path, or generate the local proto messages to the generated services.
Making the `Generator` public seemed like …

Publicize prost service generator

---

CHANGELOG.md
Cargo.toml
README.md
compiler/Cargo.toml
grpc-sys/Cargo.toml
health/Cargo.toml
proto/Cargo.toml

Note #625 can be released with just patch version, so not blocking this release.

*: bump 0.13.0

---

cross_compile.md
src/call/client.rs
src/call/server.rs
src/metadata.rs

Resolution of MacOS build issue I outlined in https://github.com/tikv/grpc-rs/issues/654 and related context to cc-rs and cmake. I'd suggested removing `uses_cx11`, which was confusingly appending to the system output of OS value and also removing the example from the documentation comment and example in [cross_compile.md](https://github.com/tikv/grpc-rs/blob/master/cross_compile.md) under All diff in fn build_grpc

remove uses_cxx11 call in build_grpc causing macos build failure
