grpc-sys/grpc_wrap.c, grpc-sys/src/lib.rs
- add more interfaces
- allow set tag explicitly
=> adjust ffi

.travis.yml
Only Linux and OS X is tested. We may need to configure [appveyor](https://www.appveyor.com/) to test on windows in the future too.
=> *: add ci check

src/async/lock.rs, src/async/mod.rs, src/async/promise.rs, src/error.rs
Promise is used to notify future that a task is completed. It's necessary when trying to communicating with c event loop (grpc_completion_queue).
=> *: introduce promise

.gitignore, src/async/mod.rs, src/async/promise.rs, src/call/mod.rs, src/lib.rs
Add basic call functions, client call and server call will be implemented in other prs respectively.
=> impl call base

compiler/src/codegen.rs, src/async/callback.rs, src/async/mod.rs, src/call/mod.rs, src/call/server.rs, src/lib.rs
This pr adds functions needed to handle rpc on server side.
=> add server call

compiler/src/codegen.rs
req -> req/stream, resp -> sink
=> compiler: update argument names.

src/async/mod.rs, src/env.rs
=> env: add thread name to Environment

src/call/client.rs, src/call/mod.rs, src/lib.rs
This pr adds functions needed to handle rpc on server side.
=> add client call

.gitmodules, Cargo.toml, grpc-sys/Cargo.toml, grpc-sys/build.rs
=> grpc-sys: add submodule, now static link

.travis.yml, grpc-sys/build.rs
clean up redundant code and enable ssl by default.
=> refactor build script and support ssl

src/call/client.rs, src/client.rs, src/lib.rs
Now we can use a functional client.
=> implement client

src/async/promise.rs
Read message doesn't always succeed. In that case we need to stop the sink.
=> fix read failure

Cargo.toml, compiler/src/codegen.rs, src/call/client.rs, src/call/mod.rs, src/call/server.rs, src/channel.rs, src/client.rs, src/codec.rs, src/error.rs, src/lib.rs, src/server.rs
So serialization and deserialization can be customized.
=> introduce marshaller

Cargo.toml, examples/route_guide/client.rs, examples/route_guide/db.json, examples/route_guide/server.rs, examples/route_guide/util.rs
The example route_guide_server and route_guide_client can be used with any client or server implemented in other language.
=> add route guide example

compiler/src/codegen.rs, examples/route_guide/client.rs, src/async/callback.rs, src/async/mod.rs, src/call/client.rs, src/call/mod.rs, src/call/server.rs, src/client.rs, src/error.rs, src/lib.rs
When server stop the handling earlier, client should stop sending any further requests.
=> client: support stop early

Cargo.toml, examples/hello_world/client.rs, examples/hello_world/server.rs, proto/proto/example/helloworld.proto
=> add greeter example

Cargo.toml, benchmark/Cargo.toml, benchmark/src/error.rs, benchmark/src/lib.rs, benchmark/src/util.rs
This pr add the basic structure of benchmark suit.
=> add benchmark utils

src/channel.rs
=> add tcp read chunk size option

grpc-sys/grpc_wrap.c
ref: https://github.com/grpc/grpc/commit/06eb057eb76d62ca6ee0987b9b2fae1befbff78a
=> c-wrap: fix memory leak

src/async/executor.rs, src/async/mod.rs, src/async/promise.rs, src/call/mod.rs, src/channel.rs, src/cq.rs, src/env.rs, src/lib.rs, src/util.rs
It's a waste when triggering an alarm will notify current thread.
=> async: reduce alarm

grpc-sys/src/lib.rs, src/channel.rs, src/lib.rs
=> add compression options

.travis.yml, Cargo.toml, compiler/Cargo.toml, interop/Cargo.toml, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/client.rs, interop/src/lib.rs, interop/src/server.rs, interop/tests/tests.rs
ref: https://github.com/grpc/grpc/blob/v1.3.x/doc/interop-test-descriptions.md
=> add Interoperability test suit

.travis.yml, Cargo.toml, benchmark/README.md, grpc-sys/Cargo.toml, grpc-sys/build.rs, grpc-sys/grpc_wrap.c, grpc-sys/src/lib.rs, src/async/mod.rs, src/call/client.rs, src/call/mod.rs, src/cq.rs
This pr upgrade grpc to 1.4.0 and enable static-link by default.
=> Upgrade grpc-core to 1.4.0

Cargo.toml, README.md
@queenypingcap @siddontang PTAL
=> add basic readme

Cargo.toml, benchmark/Cargo.toml, benchmark/src/lib.rs, benchmark/src/main.rs, compiler/Cargo.toml, compiler/src/bin/grpc_rust_plugin.rs, compiler/src/codegen.rs, compiler/src/util.rs, examples/hello_world/client.rs, examples/hello_world/server.rs, examples/route_guide/client.rs, examples/route_guide/server.rs, examples/route_guide/util.rs, grpc-sys/Cargo.toml, interop/Cargo.toml, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/lib.rs, interop/tests/tests.rs, proto/Cargo.toml, proto/build.rs, proto/src/lib.rs, proto/src/util.rs, src/lib.rs
We will publish this project on crates.io as grpcio later.
=> *: rename grpc to grpcio

benchmark/src/bench.rs, benchmark/src/client.rs, benchmark/src/main.rs, benchmark/src/server.rs, benchmark/src/util.rs, benchmark/src/worker.rs, compiler/src/codegen.rs, examples/route_guide/client.rs, examples/route_guide/server.rs, examples/route_guide/util.rs, grpc-sys/build.rs, grpc-sys/src/lib.rs, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/client.rs, interop/src/lib.rs, interop/src/server.rs, interop/tests/tests.rs, proto/build.rs, src/async/executor.rs, src/call/client.rs, src/call/mod.rs, src/call/server.rs, src/channel.rs, src/client.rs, src/credentials.rs, src/lib.rs, src/server.rs
To keep consistent with TiKV project.
=> *: format code with rustfmt-nightly 0.2.1

benchmark/src/client.rs, benchmark/src/lib.rs, examples/hello_world/client.rs, examples/hello_world/server.rs, examples/route_guide/client.rs, examples/route_guide/server.rs, examples/route_guide/util.rs, grpc-sys/build.rs, interop/src/client.rs, interop/src/lib.rs, interop/src/server.rs, interop/tests/tests.rs, src/async/executor.rs, src/lib.rs
Some types and functions are deprecated.
=> *: make it compatible with latest futures

src/call/mod.rs, src/call/server.rs
=> clear buffer hint when sending metadata

benchmark/src/util.rs, grpc-sys/Cargo.toml
I thought there is no changes in grpcio-sys, but I was wrong.
=> grpcio-sys: update version

Cargo.toml, examples/hello_world/client.rs, examples/hello_world/server.rs, examples/log_util.rs, examples/route_guide/client.rs, examples/route_guide/server.rs, proto/Cargo.toml, proto/src/lib.rs, proto/src/util.rs
Prepare to publish the grpcio-proto sub crate.
=> adjust proto

grpc-sys/build.rs, grpc-sys/src/lib.rs, proto/src/util.rs, src/channel.rs, src/credentials.rs, src/server.rs
=> *: format files

.travis.yml, grpc-sys/src/lib.rs, src/async/executor.rs, src/server.rs, tests/alarm.rs
=> Fix alarm usages

grpc-sys/build.rs, grpc-sys/grpc_wrap.c
=> fix link error on windows when building with default feature

tests/cases/alarm.rs, tests/cases/health_check.rs, tests/cases/mod.rs, tests/tests.rs
So there will be only one integration test binary.
=> tests: rearrange integration tests

README.md
Add the docs icon
PTAL @BusyJay @overvenus
=> Add docs icon

src/async/executor.rs
So polling a future won't block notifying. If they share the same lock, it's easy lead to deadlock. For example, polling future A tries to notify future B in grpc context, and future B is also trying to notify future A in other thread. If the other thread also uses one lock for polling and notifying then there is a deadlock.
=> executor: use a different lock for notify

src/channel.rs
It's created by a builder so we should link to it. :)
=> Document how to build a channel.

README.md
I always forget the command and like that, you just copy-paste and here you go!
=> Add instruction for first build

CHANGELOG.md, Cargo.toml, README.md, compiler/Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml
=> Bump to v0.4.0

.travis.yml, benchmark/src/bench.rs, benchmark/src/client.rs, benchmark/src/main.rs, benchmark/src/worker.rs, compiler/src/codegen.rs, examples/route_guide/server.rs, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/server.rs, tests/cases/cancel.rs, tests/cases/kick.rs
Clippy is now on stable! :tada:
=> Use stable clippy

README.md, cross_compile.md, grpc-sys/build.rs
=> cross compile grpc-rs to windows under *nix

CHANGELOG.md
We will release v0.4.1 with a few features and bug fixes. Here is the change log.
=> Update change log for v0.4.1

.travis.yml, benchmark/src/bench.rs, benchmark/src/client.rs, benchmark/src/main.rs, benchmark/src/server.rs, benchmark/src/worker.rs, compiler/src/codegen.rs, examples/route_guide/server.rs, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/server.rs, src/cq.rs, tests/cases/cancel.rs, tests/cases/kick.rs
trying fix the ci issue in the master
related to #262
=> fix master CI

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, benchmark/src/bench.rs, benchmark/src/client.rs, benchmark/src/main.rs, benchmark/src/server.rs, benchmark/src/worker.rs, compiler/src/codegen.rs, cross_compile.md, examples/route_guide/server.rs, grpc-sys/Cargo.toml, grpc-sys/build.rs, interop/src/bin/client.rs, interop/src/bin/server.rs, interop/src/server.rs, src/cq.rs, src/error.rs, tests/cases/cancel.rs, tests/cases/kick.rs
Bump to v0.4.2, changes:
- Cross compile grpc-rs to windows under *nix (#169)
- Upgrade gRPC core library to v1.17.2 (#264)
=> Bump v0.4.2

CHANGELOG.md, Cargo.toml, benchmark/src/client.rs, compiler/Cargo.toml, compiler/src/codegen.rs, interop/Cargo.toml, proto/Cargo.toml
Remove tilde requirements `~2.0` of protobuf.
=>  Bump v0.4.3

benchmark/src/client.rs, compiler/src/codegen.rs
Address into_iter_on_ref lints.
=> compiler, benchmark: address into_iter_on_ref lints

README.md
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
See #274
=> Add binutils version

interop/src/server.rs
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
Fix a typo
=> Fixes #286

CHANGELOG.md, Cargo.toml, compiler/Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml
Update change log and bump to 0.5.0
=> Bump to 0.5.0

CHANGELOG.md, Cargo.toml
=> Bump to 0.5.0-alpha.1

CHANGELOG.md, src/task/executor.rs, tests/cases/kick.rs
Signed-off-by: Keyi Xie <xiekeyi98@gmail.com>
Fix misspell in comments and CHANGELOG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/grpc-rs/314)
=> *: fix misspell

Cargo.toml, grpc-sys/Cargo.toml, grpc-sys/build.rs
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
This PR addresses #316.
=> Fix #316: support `-fno-omit-frame-pointer` flag via a feature

.travis.yml, Cargo.toml, README.md, scripts/lint-grpc-sys.sh
1. Add Windows support
2. update `llvm` dependency for `bindgen`
Related issue #335
=> grpcio: update travis

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
=> *: bump to 0.5.0-alpha.3

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml
=> *: bump 0.5.0-alpha.4

.travis.yml, grpc-sys/src/lib.rs, src/async/executor.rs, src/error.rs, src/server.rs
Fix a segfault bug in grpc core https://github.com/pingcap/grpc/pull/32
=> *: update grpc c core in v0.3.x

.travis.yml, grpc-sys/src/lib.rs, src/async/executor.rs, src/error.rs, src/server.rs
Fix a segfault bug in grpc core pingcap/grpc#32
=> *: update grpc c core in v0.4.x

src/task/executor.rs
Fix a segfault bug in grpc core https://github.com/pingcap/grpc/pull/32
=> *: update grpc c core in master

examples/hello_world/server.rs, grpc-sys/grpc_wrap.cc, grpc-sys/src/lib.rs, src/channel.rs, src/lib.rs, src/quota.rs
=> grpcio: add resource quota support

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml
Signed-off-by: Liqi Geng <gengliqiii@gmail.com>
=> *: bump 0.4.5

benchmark/src/lib.rs, proto/src/lib.rs, src/lib.rs, src/metadata.rs, tests/tests.rs
Make it compatible with latest rust.
=> fix compilation warnings

.travis.yml, Cargo.toml, grpc-sys/Cargo.toml, grpc-sys/build.rs
=> Support openssl-vendored feature

src/call/mod.rs
Signed-off-by: qupeng <qupeng@pingcap.com>
=> shrink sink internal buffer if need (#407)

.travis.yml, grpc-sys/build.rs
Fix improper CI configuration that makes CMake re-run configuration generation.
=> Fix CI cache

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml
Signed-off-by: qupeng <qupeng@pingcap.com>
=> bump to 0.4.7

CHANGELOG.md, Cargo.toml
Signed-off-by: qupeng <qupeng@pingcap.com>
=> bump to 0.3.2

src/call/mod.rs, src/error.rs
Resolves #432
**What it does:**
- Impl Display for RpcStatus and RpcStatusCode
- Update Display impl for grpcio::Error
Signed-off-by: Elrendio <oscar.walter@ens.fr>
=> Better Display impl for grpcio::Error

tests-and-examples/tests/cases/cancel.rs
Add judgement for the result of `unbounded_send()`
Close #439 
=> Fix test_early_exit

CHANGELOG.md, Cargo.toml, compiler/Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
=> *: bump 0.5.0

README.md, src/channel.rs, tests-and-examples/Cargo.toml, tests-and-examples/examples/load_balancing/client.rs, tests-and-examples/examples/load_balancing/server.rs
Load balancing is supported in the grpc c core, but load report is not
implemented yet. It's hard to implement load report without census API.
Related grpc/grpc#22418.
=> *: clarify load balancing status

src/server.rs, tests-and-examples/tests/cases/misc.rs
It's supported by c core, we just need to allow it as parameter.
Close #296.
=> *: support unix domain socket

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml
Bump 0.5.1 to include several recent updates.
=> *: bump 0.5.1

.github/workflows/ci.yml, .travis.yml
Travis has wasted a lot of our time, maybe we should try something new.
=> Switch to github action

Cargo.toml, src/call/server.rs
=> Make clippy happy

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml, src/channel.rs
Bump 0.5.4 to include #474 update.
=> *: bump 0.5.4

grpc-sys/bindings/aarch64-unknown-linux-gnu-bindings.rs, grpc-sys/bindings/x86_64-unknown-linux-gnu-bindings.rs, src/server.rs, tests-and-examples/tests/cases/misc.rs
=> Fix the bug that drop server cannot shutdown self

src/channel.rs
=> channel: fix incorrect parameter doc

CHANGELOG.md, Cargo.toml, compiler/Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
=> *: bump 0.7.0

CHANGELOG.md, Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
=> *: bump 0.7.1

CHANGELOG.md, Cargo.toml, compiler/Cargo.toml, grpc-sys/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
=> *: bump version to 0.8.0

grpc-sys/build.rs, src/lib.rs
Ref #528.
This is a hot fix. A real fix needs to remove protobuf-build completely.
=> *: make 0.8.x work with 0.9.x compiler

CHANGELOG.md, Cargo.toml, compiler/src/util.rs, grpc-sys/build.rs, interop/src/server.rs, src/call/client.rs, src/call/mod.rs, src/cq.rs, src/lib.rs, src/metadata.rs
=> *: make 0.7.x work with 0.9.x compiler

src/quota.rs
Add clone for `ResourceQuota` to allow dynamically adjust the memory quota after grpc server is started.
=> implement Clone for ResourceQuota

src/channel.rs
Signed-off-by: Antoine.orhant <antoine.orhant@gmail.com>
=> feat: Add support for GRPC_ARG_ENABLE_HTTP_PROXY parameter

Cargo.toml, compiler/Cargo.toml, health/Cargo.toml, proto/Cargo.toml, tests-and-examples/Cargo.toml
Fixes #581. I verified my project for which I filed that issue builds with this change.
=> Bump prost 0.9 -> 0.10
